spring.application.name=airline-management

spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/airline_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
gemini.api.key=${GEMINI_API_KEY}
